language: objective-c
osx_image: xcode9
branches:
  only:
    - travis
    - master
before_install:
  - rvm get stable --auto-dotfiles
  - rvm use 2.4 --install --binary --fuzzy
  - (ruby --version)
gemfile:
  - Gemfile
script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake pod:install clean spec
