language: objective-c
before_install:
  - (ruby --version)
  - sudo motion update
gemfile:
  - Gemfile
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - bundle exec rake clean
script:
  - bundle exec rake spec
