language: objective-c
osx_image: xcode7.2
before_install:
  - (ruby --version)
  - sudo motion update
gemfile:
  - Gemfile
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake pod:install
before_script:
  - bundle exec rake clean
script:
  - bundle exec rake spec
